# Generated by Django 4.1 on 2022-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('title', models.CharField(max_length=100)),
                ('pic_url', models.URLField(blank=True)),
                ('download_url', models.URLField(blank=True)),
                ('blockchain_keys', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
