# Generated by Django 4.1 on 2022-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_exhibit_items_fungibility_exhibit_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit_items',
            name='buystatus',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
